#!/bin/bash

VERSION=3.3.2
PACKAGE=hmmer
TOOL=hmmpgmd
DIRECTORY=$(dirname $0)
LANG=C

PERSISTENT_FILE_STORAGE=/ocean
if [ -d $PERSISTENT_FILE_STORAGE ]; then
        OPTIONS="-B $PERSISTENT_FILE_STORAGE"
fi

if [ -d /local ]; then
        OPTIONS=$OPTIONS" -B /local"
fi

singularity exec $OPTIONS $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
